webtalk_init -webtalk_dir C:\\Users\\benci\\Documents\\University\\SEM4\\SPROJ4\\Software\\Plotter_Driver_v2\\Plotter_Driver_v2.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2025-05-21 16:45:50" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ka4f99qiltphi487d7hv8u9kbq" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-12500H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3110 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "68.426 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1747824790531" -context "sdk\\\\bsp/1747824790531"
webtalk_add_data -client sdk -key hwid -value "1747741613241" -context "sdk\\\\bsp/1747824790531"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1747824790531"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\bsp/1747824790531"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1747824790531"
webtalk_add_data -client sdk -key uid -value "1747824797429" -context "sdk\\\\application/1747824797429"
webtalk_add_data -client sdk -key hwid -value "1747741613241" -context "sdk\\\\application/1747824797429"
webtalk_add_data -client sdk -key bspid -value "1747824790531" -context "sdk\\\\application/1747824797429"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1747824797429"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1747824797429"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1747824797429"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1747824797429"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1747824797429"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1747824797429"
webtalk_add_data -client sdk -key projSize -value "523.26953125" -context "sdk\\\\application/1747824797429"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1747838750236"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1747838750236"
webtalk_add_data -client sdk -key BootgenCount -value "4" -context "sdk\\\\bsp/1747838750236"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1747838750236"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1747838750236"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1747838750236"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1747838750236"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1747838750236"
webtalk_transmit -clientid 3495443813 -regid "" -xml C:\\Users\\benci\\Documents\\University\\SEM4\\SPROJ4\\Software\\Plotter_Driver_v2\\Plotter_Driver_v2.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\benci\\Documents\\University\\SEM4\\SPROJ4\\Software\\Plotter_Driver_v2\\Plotter_Driver_v2.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\benci\\Documents\\University\\SEM4\\SPROJ4\\Software\\Plotter_Driver_v2\\Plotter_Driver_v2.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
